import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/UIComponents/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const dynamic = 'force-dynamic';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex'>
             <div className=' w-1/5'>
              {/* @ts-ignore */}
             <Sidebar />
             </div>
             <div className='w-4/5 bg-slate-100'>
               {children}
            </div>

          </div>
      </body>
    </html>
  )
}
