import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const dynamic = 'force-dynamic';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex justify-between '>
          <div className='w-[20%] max-h-[100hv] fixed top-0 bottom-0 z-50'>
          <Sidebar />
          </div>
          <div className=' ml-[20%] w-[80%] max-h-[100hv] p-4'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
